// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROJECT_MYENGINE_PROJECT_H_
#define FLATBUFFERS_GENERATED_PROJECT_MYENGINE_PROJECT_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace MyEngine {
namespace Project {

struct Project;
struct ProjectBuilder;

struct Project FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ProjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VERSION = 6,
    VT_MAIN_SCENE_FILE = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VERSION);
  }
  const ::flatbuffers::String *main_scene_file() const {
    return GetPointer<const ::flatbuffers::String *>(VT_MAIN_SCENE_FILE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_VERSION) &&
           verifier.VerifyString(version()) &&
           VerifyOffset(verifier, VT_MAIN_SCENE_FILE) &&
           verifier.VerifyString(main_scene_file()) &&
           verifier.EndTable();
  }
};

struct ProjectBuilder {
  typedef Project Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Project::VT_NAME, name);
  }
  void add_version(::flatbuffers::Offset<::flatbuffers::String> version) {
    fbb_.AddOffset(Project::VT_VERSION, version);
  }
  void add_main_scene_file(::flatbuffers::Offset<::flatbuffers::String> main_scene_file) {
    fbb_.AddOffset(Project::VT_MAIN_SCENE_FILE, main_scene_file);
  }
  explicit ProjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Project> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Project>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Project> CreateProject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> version = 0,
    ::flatbuffers::Offset<::flatbuffers::String> main_scene_file = 0) {
  ProjectBuilder builder_(_fbb);
  builder_.add_main_scene_file(main_scene_file);
  builder_.add_version(version);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Project> CreateProjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *version = nullptr,
    const char *main_scene_file = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto version__ = version ? _fbb.CreateString(version) : 0;
  auto main_scene_file__ = main_scene_file ? _fbb.CreateString(main_scene_file) : 0;
  return MyEngine::Project::CreateProject(
      _fbb,
      name__,
      version__,
      main_scene_file__);
}

inline const MyEngine::Project::Project *GetProject(const void *buf) {
  return ::flatbuffers::GetRoot<MyEngine::Project::Project>(buf);
}

inline const MyEngine::Project::Project *GetSizePrefixedProject(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<MyEngine::Project::Project>(buf);
}

inline bool VerifyProjectBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<MyEngine::Project::Project>(nullptr);
}

inline bool VerifySizePrefixedProjectBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<MyEngine::Project::Project>(nullptr);
}

inline void FinishProjectBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MyEngine::Project::Project> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedProjectBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MyEngine::Project::Project> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Project
}  // namespace MyEngine

#endif  // FLATBUFFERS_GENERATED_PROJECT_MYENGINE_PROJECT_H_
