// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SCENE_MYENGINE_SCENE_H_
#define FLATBUFFERS_GENERATED_SCENE_MYENGINE_SCENE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace MyEngine {
namespace Scene {

struct Vec3;

struct Quat;

struct Transform;
struct TransformBuilder;

struct Material;
struct MaterialBuilder;

struct MeshRenderer;
struct MeshRendererBuilder;

struct Light;
struct LightBuilder;

struct Component;
struct ComponentBuilder;

struct GameObject;
struct GameObjectBuilder;

struct Scene;
struct SceneBuilder;

enum LightType : int8_t {
  LightType_Directional = 0,
  LightType_Point = 1,
  LightType_Spot = 2,
  LightType_MIN = LightType_Directional,
  LightType_MAX = LightType_Spot
};

inline const LightType (&EnumValuesLightType())[3] {
  static const LightType values[] = {
    LightType_Directional,
    LightType_Point,
    LightType_Spot
  };
  return values;
}

inline const char * const *EnumNamesLightType() {
  static const char * const names[4] = {
    "Directional",
    "Point",
    "Spot",
    nullptr
  };
  return names;
}

inline const char *EnumNameLightType(LightType e) {
  if (::flatbuffers::IsOutRange(e, LightType_Directional, LightType_Spot)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLightType()[index];
}

enum ComponentData : uint8_t {
  ComponentData_NONE = 0,
  ComponentData_MeshRenderer = 1,
  ComponentData_Light = 2,
  ComponentData_MIN = ComponentData_NONE,
  ComponentData_MAX = ComponentData_Light
};

inline const ComponentData (&EnumValuesComponentData())[3] {
  static const ComponentData values[] = {
    ComponentData_NONE,
    ComponentData_MeshRenderer,
    ComponentData_Light
  };
  return values;
}

inline const char * const *EnumNamesComponentData() {
  static const char * const names[4] = {
    "NONE",
    "MeshRenderer",
    "Light",
    nullptr
  };
  return names;
}

inline const char *EnumNameComponentData(ComponentData e) {
  if (::flatbuffers::IsOutRange(e, ComponentData_NONE, ComponentData_Light)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesComponentData()[index];
}

template<typename T> struct ComponentDataTraits {
  static const ComponentData enum_value = ComponentData_NONE;
};

template<> struct ComponentDataTraits<MyEngine::Scene::MeshRenderer> {
  static const ComponentData enum_value = ComponentData_MeshRenderer;
};

template<> struct ComponentDataTraits<MyEngine::Scene::Light> {
  static const ComponentData enum_value = ComponentData_Light;
};

bool VerifyComponentData(::flatbuffers::Verifier &verifier, const void *obj, ComponentData type);
bool VerifyComponentDataVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Quat FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Quat()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Quat(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Quat, 16);

struct Transform FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TransformBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITION = 4,
    VT_ROTATION = 6,
    VT_SCALE = 8
  };
  const MyEngine::Scene::Vec3 *position() const {
    return GetStruct<const MyEngine::Scene::Vec3 *>(VT_POSITION);
  }
  const MyEngine::Scene::Vec3 *rotation() const {
    return GetStruct<const MyEngine::Scene::Vec3 *>(VT_ROTATION);
  }
  const MyEngine::Scene::Vec3 *scale() const {
    return GetStruct<const MyEngine::Scene::Vec3 *>(VT_SCALE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<MyEngine::Scene::Vec3>(verifier, VT_POSITION, 4) &&
           VerifyField<MyEngine::Scene::Vec3>(verifier, VT_ROTATION, 4) &&
           VerifyField<MyEngine::Scene::Vec3>(verifier, VT_SCALE, 4) &&
           verifier.EndTable();
  }
};

struct TransformBuilder {
  typedef Transform Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_position(const MyEngine::Scene::Vec3 *position) {
    fbb_.AddStruct(Transform::VT_POSITION, position);
  }
  void add_rotation(const MyEngine::Scene::Vec3 *rotation) {
    fbb_.AddStruct(Transform::VT_ROTATION, rotation);
  }
  void add_scale(const MyEngine::Scene::Vec3 *scale) {
    fbb_.AddStruct(Transform::VT_SCALE, scale);
  }
  explicit TransformBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Transform> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Transform>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Transform> CreateTransform(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const MyEngine::Scene::Vec3 *position = nullptr,
    const MyEngine::Scene::Vec3 *rotation = nullptr,
    const MyEngine::Scene::Vec3 *scale = nullptr) {
  TransformBuilder builder_(_fbb);
  builder_.add_scale(scale);
  builder_.add_rotation(rotation);
  builder_.add_position(position);
  return builder_.Finish();
}

struct Material FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MaterialBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_BASE_COLOR = 4,
    VT_SHININESS = 6,
    VT_DIFFUSE_TEXTURE_PATH = 8,
    VT_SPECULAR_TEXTURE_PATH = 10,
    VT_NORMAL_TEXTURE_PATH = 12
  };
  const MyEngine::Scene::Vec3 *base_color() const {
    return GetStruct<const MyEngine::Scene::Vec3 *>(VT_BASE_COLOR);
  }
  float shininess() const {
    return GetField<float>(VT_SHININESS, 0.0f);
  }
  const ::flatbuffers::String *diffuse_texture_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_DIFFUSE_TEXTURE_PATH);
  }
  const ::flatbuffers::String *specular_texture_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SPECULAR_TEXTURE_PATH);
  }
  const ::flatbuffers::String *normal_texture_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NORMAL_TEXTURE_PATH);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<MyEngine::Scene::Vec3>(verifier, VT_BASE_COLOR, 4) &&
           VerifyField<float>(verifier, VT_SHININESS, 4) &&
           VerifyOffset(verifier, VT_DIFFUSE_TEXTURE_PATH) &&
           verifier.VerifyString(diffuse_texture_path()) &&
           VerifyOffset(verifier, VT_SPECULAR_TEXTURE_PATH) &&
           verifier.VerifyString(specular_texture_path()) &&
           VerifyOffset(verifier, VT_NORMAL_TEXTURE_PATH) &&
           verifier.VerifyString(normal_texture_path()) &&
           verifier.EndTable();
  }
};

struct MaterialBuilder {
  typedef Material Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_base_color(const MyEngine::Scene::Vec3 *base_color) {
    fbb_.AddStruct(Material::VT_BASE_COLOR, base_color);
  }
  void add_shininess(float shininess) {
    fbb_.AddElement<float>(Material::VT_SHININESS, shininess, 0.0f);
  }
  void add_diffuse_texture_path(::flatbuffers::Offset<::flatbuffers::String> diffuse_texture_path) {
    fbb_.AddOffset(Material::VT_DIFFUSE_TEXTURE_PATH, diffuse_texture_path);
  }
  void add_specular_texture_path(::flatbuffers::Offset<::flatbuffers::String> specular_texture_path) {
    fbb_.AddOffset(Material::VT_SPECULAR_TEXTURE_PATH, specular_texture_path);
  }
  void add_normal_texture_path(::flatbuffers::Offset<::flatbuffers::String> normal_texture_path) {
    fbb_.AddOffset(Material::VT_NORMAL_TEXTURE_PATH, normal_texture_path);
  }
  explicit MaterialBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Material> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Material>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Material> CreateMaterial(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const MyEngine::Scene::Vec3 *base_color = nullptr,
    float shininess = 0.0f,
    ::flatbuffers::Offset<::flatbuffers::String> diffuse_texture_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> specular_texture_path = 0,
    ::flatbuffers::Offset<::flatbuffers::String> normal_texture_path = 0) {
  MaterialBuilder builder_(_fbb);
  builder_.add_normal_texture_path(normal_texture_path);
  builder_.add_specular_texture_path(specular_texture_path);
  builder_.add_diffuse_texture_path(diffuse_texture_path);
  builder_.add_shininess(shininess);
  builder_.add_base_color(base_color);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Material> CreateMaterialDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const MyEngine::Scene::Vec3 *base_color = nullptr,
    float shininess = 0.0f,
    const char *diffuse_texture_path = nullptr,
    const char *specular_texture_path = nullptr,
    const char *normal_texture_path = nullptr) {
  auto diffuse_texture_path__ = diffuse_texture_path ? _fbb.CreateString(diffuse_texture_path) : 0;
  auto specular_texture_path__ = specular_texture_path ? _fbb.CreateString(specular_texture_path) : 0;
  auto normal_texture_path__ = normal_texture_path ? _fbb.CreateString(normal_texture_path) : 0;
  return MyEngine::Scene::CreateMaterial(
      _fbb,
      base_color,
      shininess,
      diffuse_texture_path__,
      specular_texture_path__,
      normal_texture_path__);
}

struct MeshRenderer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshRendererBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ASSET_PATH = 4,
    VT_MATERIAL = 6
  };
  const ::flatbuffers::String *asset_path() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ASSET_PATH);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<MyEngine::Scene::Material>> *material() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<MyEngine::Scene::Material>> *>(VT_MATERIAL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ASSET_PATH) &&
           verifier.VerifyString(asset_path()) &&
           VerifyOffset(verifier, VT_MATERIAL) &&
           verifier.VerifyVector(material()) &&
           verifier.VerifyVectorOfTables(material()) &&
           verifier.EndTable();
  }
};

struct MeshRendererBuilder {
  typedef MeshRenderer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_asset_path(::flatbuffers::Offset<::flatbuffers::String> asset_path) {
    fbb_.AddOffset(MeshRenderer::VT_ASSET_PATH, asset_path);
  }
  void add_material(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MyEngine::Scene::Material>>> material) {
    fbb_.AddOffset(MeshRenderer::VT_MATERIAL, material);
  }
  explicit MeshRendererBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MeshRenderer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MeshRenderer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MeshRenderer> CreateMeshRenderer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> asset_path = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MyEngine::Scene::Material>>> material = 0) {
  MeshRendererBuilder builder_(_fbb);
  builder_.add_material(material);
  builder_.add_asset_path(asset_path);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MeshRenderer> CreateMeshRendererDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *asset_path = nullptr,
    const std::vector<::flatbuffers::Offset<MyEngine::Scene::Material>> *material = nullptr) {
  auto asset_path__ = asset_path ? _fbb.CreateString(asset_path) : 0;
  auto material__ = material ? _fbb.CreateVector<::flatbuffers::Offset<MyEngine::Scene::Material>>(*material) : 0;
  return MyEngine::Scene::CreateMeshRenderer(
      _fbb,
      asset_path__,
      material__);
}

struct Light FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LightBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_LIGHT_TYPE = 4,
    VT_AMBIENT = 6,
    VT_DIFFUSE = 8,
    VT_SPECULAR = 10,
    VT_INTENSITY = 12,
    VT_CONSTANT = 14,
    VT_LINEAR = 16,
    VT_QUADRATIC = 18,
    VT_CUTOFF = 20,
    VT_OUTER_CUTOFF = 22
  };
  MyEngine::Scene::LightType light_type() const {
    return static_cast<MyEngine::Scene::LightType>(GetField<int8_t>(VT_LIGHT_TYPE, 0));
  }
  const MyEngine::Scene::Vec3 *ambient() const {
    return GetStruct<const MyEngine::Scene::Vec3 *>(VT_AMBIENT);
  }
  const MyEngine::Scene::Vec3 *diffuse() const {
    return GetStruct<const MyEngine::Scene::Vec3 *>(VT_DIFFUSE);
  }
  const MyEngine::Scene::Vec3 *specular() const {
    return GetStruct<const MyEngine::Scene::Vec3 *>(VT_SPECULAR);
  }
  float intensity() const {
    return GetField<float>(VT_INTENSITY, 0.0f);
  }
  float constant() const {
    return GetField<float>(VT_CONSTANT, 0.0f);
  }
  float linear() const {
    return GetField<float>(VT_LINEAR, 0.0f);
  }
  float quadratic() const {
    return GetField<float>(VT_QUADRATIC, 0.0f);
  }
  float cutoff() const {
    return GetField<float>(VT_CUTOFF, 0.0f);
  }
  float outer_cutoff() const {
    return GetField<float>(VT_OUTER_CUTOFF, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_LIGHT_TYPE, 1) &&
           VerifyField<MyEngine::Scene::Vec3>(verifier, VT_AMBIENT, 4) &&
           VerifyField<MyEngine::Scene::Vec3>(verifier, VT_DIFFUSE, 4) &&
           VerifyField<MyEngine::Scene::Vec3>(verifier, VT_SPECULAR, 4) &&
           VerifyField<float>(verifier, VT_INTENSITY, 4) &&
           VerifyField<float>(verifier, VT_CONSTANT, 4) &&
           VerifyField<float>(verifier, VT_LINEAR, 4) &&
           VerifyField<float>(verifier, VT_QUADRATIC, 4) &&
           VerifyField<float>(verifier, VT_CUTOFF, 4) &&
           VerifyField<float>(verifier, VT_OUTER_CUTOFF, 4) &&
           verifier.EndTable();
  }
};

struct LightBuilder {
  typedef Light Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_light_type(MyEngine::Scene::LightType light_type) {
    fbb_.AddElement<int8_t>(Light::VT_LIGHT_TYPE, static_cast<int8_t>(light_type), 0);
  }
  void add_ambient(const MyEngine::Scene::Vec3 *ambient) {
    fbb_.AddStruct(Light::VT_AMBIENT, ambient);
  }
  void add_diffuse(const MyEngine::Scene::Vec3 *diffuse) {
    fbb_.AddStruct(Light::VT_DIFFUSE, diffuse);
  }
  void add_specular(const MyEngine::Scene::Vec3 *specular) {
    fbb_.AddStruct(Light::VT_SPECULAR, specular);
  }
  void add_intensity(float intensity) {
    fbb_.AddElement<float>(Light::VT_INTENSITY, intensity, 0.0f);
  }
  void add_constant(float constant) {
    fbb_.AddElement<float>(Light::VT_CONSTANT, constant, 0.0f);
  }
  void add_linear(float linear) {
    fbb_.AddElement<float>(Light::VT_LINEAR, linear, 0.0f);
  }
  void add_quadratic(float quadratic) {
    fbb_.AddElement<float>(Light::VT_QUADRATIC, quadratic, 0.0f);
  }
  void add_cutoff(float cutoff) {
    fbb_.AddElement<float>(Light::VT_CUTOFF, cutoff, 0.0f);
  }
  void add_outer_cutoff(float outer_cutoff) {
    fbb_.AddElement<float>(Light::VT_OUTER_CUTOFF, outer_cutoff, 0.0f);
  }
  explicit LightBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Light> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Light>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Light> CreateLight(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    MyEngine::Scene::LightType light_type = MyEngine::Scene::LightType_Directional,
    const MyEngine::Scene::Vec3 *ambient = nullptr,
    const MyEngine::Scene::Vec3 *diffuse = nullptr,
    const MyEngine::Scene::Vec3 *specular = nullptr,
    float intensity = 0.0f,
    float constant = 0.0f,
    float linear = 0.0f,
    float quadratic = 0.0f,
    float cutoff = 0.0f,
    float outer_cutoff = 0.0f) {
  LightBuilder builder_(_fbb);
  builder_.add_outer_cutoff(outer_cutoff);
  builder_.add_cutoff(cutoff);
  builder_.add_quadratic(quadratic);
  builder_.add_linear(linear);
  builder_.add_constant(constant);
  builder_.add_intensity(intensity);
  builder_.add_specular(specular);
  builder_.add_diffuse(diffuse);
  builder_.add_ambient(ambient);
  builder_.add_light_type(light_type);
  return builder_.Finish();
}

struct Component FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ComponentBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATA_TYPE = 4,
    VT_DATA = 6
  };
  MyEngine::Scene::ComponentData data_type() const {
    return static_cast<MyEngine::Scene::ComponentData>(GetField<uint8_t>(VT_DATA_TYPE, 0));
  }
  const void *data() const {
    return GetPointer<const void *>(VT_DATA);
  }
  template<typename T> const T *data_as() const;
  const MyEngine::Scene::MeshRenderer *data_as_MeshRenderer() const {
    return data_type() == MyEngine::Scene::ComponentData_MeshRenderer ? static_cast<const MyEngine::Scene::MeshRenderer *>(data()) : nullptr;
  }
  const MyEngine::Scene::Light *data_as_Light() const {
    return data_type() == MyEngine::Scene::ComponentData_Light ? static_cast<const MyEngine::Scene::Light *>(data()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_DATA_TYPE, 1) &&
           VerifyOffset(verifier, VT_DATA) &&
           VerifyComponentData(verifier, data(), data_type()) &&
           verifier.EndTable();
  }
};

template<> inline const MyEngine::Scene::MeshRenderer *Component::data_as<MyEngine::Scene::MeshRenderer>() const {
  return data_as_MeshRenderer();
}

template<> inline const MyEngine::Scene::Light *Component::data_as<MyEngine::Scene::Light>() const {
  return data_as_Light();
}

struct ComponentBuilder {
  typedef Component Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_data_type(MyEngine::Scene::ComponentData data_type) {
    fbb_.AddElement<uint8_t>(Component::VT_DATA_TYPE, static_cast<uint8_t>(data_type), 0);
  }
  void add_data(::flatbuffers::Offset<void> data) {
    fbb_.AddOffset(Component::VT_DATA, data);
  }
  explicit ComponentBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Component> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Component>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Component> CreateComponent(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    MyEngine::Scene::ComponentData data_type = MyEngine::Scene::ComponentData_NONE,
    ::flatbuffers::Offset<void> data = 0) {
  ComponentBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_data_type(data_type);
  return builder_.Finish();
}

struct GameObject FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GameObjectBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_PARENT_ID = 6,
    VT_NAME = 8,
    VT_TRANSFORM = 10,
    VT_COMPONENTS = 12
  };
  uint32_t id() const {
    return GetField<uint32_t>(VT_ID, 0);
  }
  uint32_t parent_id() const {
    return GetField<uint32_t>(VT_PARENT_ID, 0);
  }
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const MyEngine::Scene::Transform *transform() const {
    return GetPointer<const MyEngine::Scene::Transform *>(VT_TRANSFORM);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<MyEngine::Scene::Component>> *components() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<MyEngine::Scene::Component>> *>(VT_COMPONENTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_PARENT_ID, 4) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_TRANSFORM) &&
           verifier.VerifyTable(transform()) &&
           VerifyOffset(verifier, VT_COMPONENTS) &&
           verifier.VerifyVector(components()) &&
           verifier.VerifyVectorOfTables(components()) &&
           verifier.EndTable();
  }
};

struct GameObjectBuilder {
  typedef GameObject Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint32_t id) {
    fbb_.AddElement<uint32_t>(GameObject::VT_ID, id, 0);
  }
  void add_parent_id(uint32_t parent_id) {
    fbb_.AddElement<uint32_t>(GameObject::VT_PARENT_ID, parent_id, 0);
  }
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(GameObject::VT_NAME, name);
  }
  void add_transform(::flatbuffers::Offset<MyEngine::Scene::Transform> transform) {
    fbb_.AddOffset(GameObject::VT_TRANSFORM, transform);
  }
  void add_components(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MyEngine::Scene::Component>>> components) {
    fbb_.AddOffset(GameObject::VT_COMPONENTS, components);
  }
  explicit GameObjectBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<GameObject> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<GameObject>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<GameObject> CreateGameObject(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    uint32_t parent_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<MyEngine::Scene::Transform> transform = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MyEngine::Scene::Component>>> components = 0) {
  GameObjectBuilder builder_(_fbb);
  builder_.add_components(components);
  builder_.add_transform(transform);
  builder_.add_name(name);
  builder_.add_parent_id(parent_id);
  builder_.add_id(id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<GameObject> CreateGameObjectDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t id = 0,
    uint32_t parent_id = 0,
    const char *name = nullptr,
    ::flatbuffers::Offset<MyEngine::Scene::Transform> transform = 0,
    const std::vector<::flatbuffers::Offset<MyEngine::Scene::Component>> *components = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto components__ = components ? _fbb.CreateVector<::flatbuffers::Offset<MyEngine::Scene::Component>>(*components) : 0;
  return MyEngine::Scene::CreateGameObject(
      _fbb,
      id,
      parent_id,
      name__,
      transform,
      components__);
}

struct Scene FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SceneBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VERSION = 6,
    VT_GAME_OBJECTS = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::String *version() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VERSION);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<MyEngine::Scene::GameObject>> *game_objects() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<MyEngine::Scene::GameObject>> *>(VT_GAME_OBJECTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_VERSION) &&
           verifier.VerifyString(version()) &&
           VerifyOffset(verifier, VT_GAME_OBJECTS) &&
           verifier.VerifyVector(game_objects()) &&
           verifier.VerifyVectorOfTables(game_objects()) &&
           verifier.EndTable();
  }
};

struct SceneBuilder {
  typedef Scene Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Scene::VT_NAME, name);
  }
  void add_version(::flatbuffers::Offset<::flatbuffers::String> version) {
    fbb_.AddOffset(Scene::VT_VERSION, version);
  }
  void add_game_objects(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MyEngine::Scene::GameObject>>> game_objects) {
    fbb_.AddOffset(Scene::VT_GAME_OBJECTS, game_objects);
  }
  explicit SceneBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Scene> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Scene>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Scene> CreateScene(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::String> version = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<MyEngine::Scene::GameObject>>> game_objects = 0) {
  SceneBuilder builder_(_fbb);
  builder_.add_game_objects(game_objects);
  builder_.add_version(version);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Scene> CreateSceneDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const char *version = nullptr,
    const std::vector<::flatbuffers::Offset<MyEngine::Scene::GameObject>> *game_objects = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto version__ = version ? _fbb.CreateString(version) : 0;
  auto game_objects__ = game_objects ? _fbb.CreateVector<::flatbuffers::Offset<MyEngine::Scene::GameObject>>(*game_objects) : 0;
  return MyEngine::Scene::CreateScene(
      _fbb,
      name__,
      version__,
      game_objects__);
}

inline bool VerifyComponentData(::flatbuffers::Verifier &verifier, const void *obj, ComponentData type) {
  switch (type) {
    case ComponentData_NONE: {
      return true;
    }
    case ComponentData_MeshRenderer: {
      auto ptr = reinterpret_cast<const MyEngine::Scene::MeshRenderer *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ComponentData_Light: {
      auto ptr = reinterpret_cast<const MyEngine::Scene::Light *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyComponentDataVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyComponentData(
        verifier,  values->Get(i), types->GetEnum<ComponentData>(i))) {
      return false;
    }
  }
  return true;
}

inline const MyEngine::Scene::Scene *GetScene(const void *buf) {
  return ::flatbuffers::GetRoot<MyEngine::Scene::Scene>(buf);
}

inline const MyEngine::Scene::Scene *GetSizePrefixedScene(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<MyEngine::Scene::Scene>(buf);
}

inline bool VerifySceneBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<MyEngine::Scene::Scene>(nullptr);
}

inline bool VerifySizePrefixedSceneBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<MyEngine::Scene::Scene>(nullptr);
}

inline void FinishSceneBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MyEngine::Scene::Scene> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSceneBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MyEngine::Scene::Scene> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Scene
}  // namespace MyEngine

#endif  // FLATBUFFERS_GENERATED_SCENE_MYENGINE_SCENE_H_
