// SceneSerializer.cpp
#include "SceneSerializer.h"
#include "GameObject.h"
#include "Light.h" // Include all your specific light types
#include "DirectionalLight.h"
#include "PointLight.h"
#include "SpotLight.h"
#include "ResourceManager.h" // Include your resource manager

#include "scene_generated.h" // The header generated by flatc

#include "flatbuffers/flatbuffers.h"
#include <fstream>
#include <iostream>

// Include glm for math types
#include <glm/glm.hpp>


// Utility functions to convert between glm::vec3 and your FlatBuffers Vec3
MyEngine::Scene::Vec3 ToFBVec3(const glm::vec3& v) {
    return MyEngine::Scene::Vec3(v.x, v.y, v.z);
}
glm::vec3 ToGLMVec3(const MyEngine::Scene::Vec3* v) {
    return v ? glm::vec3(v->x(), v->y(), v->z()) : glm::vec3(0.0f);
}


SceneSerializer::SceneSerializer(ResourceManager* resourceManager)
    : m_resourceManager(resourceManager) {}

// --- SAVING ---

bool SceneSerializer::SaveScene(const std::filesystem::path& filePath, const std::vector<std::shared_ptr<GameObject>>& sceneRoots) {
    flatbuffers::FlatBufferBuilder builder(1024);
    
    std::vector<flatbuffers::Offset<MyEngine::Scene::GameObject>> gameObjectOffsets;
    
    // Recursively serialize all objects starting from the roots
    for (const auto& rootObject : sceneRoots) {
        SerializeObjectAndChildren(rootObject, builder, gameObjectOffsets);
    }

    auto gameObjectsVector = builder.CreateVector(gameObjectOffsets);
    auto nameString = builder.CreateString("MainScene");
    auto versionString = builder.CreateString("1.0.0");
    
    auto scene = MyEngine::Scene::CreateScene(builder, nameString, versionString, gameObjectsVector);
    builder.Finish(scene);
    
    std::ofstream outfile(filePath, std::ios::binary);
    if (!outfile) {
        std::cerr << "Error: Could not open file for writing: " << filePath << std::endl;
        return false;
    }
    outfile.write(reinterpret_cast<const char*>(builder.GetBufferPointer()), builder.GetSize());
    
    std::cout << "Scene saved successfully to " << filePath << std::endl;
    return true;
}

void SceneSerializer::SerializeObjectAndChildren(
    std::shared_ptr<GameObject> object,
    flatbuffers::FlatBufferBuilder& builder,
    std::vector<flatbuffers::Offset<MyEngine::Scene::GameObject>>& gameObjectOffsets)
{
    // --- 1. Serialize Components ---
    std::vector<flatbuffers::Offset<MyEngine::Scene::Component>> componentOffsets;
    // std::vector<flatbuffers::Offset<MyEngine::Scene::Material>> materialOffsets;

    // A. MeshRenderer Component
    // if (object->model) {
    //     // Material
    //     auto& mesh = object->model->GetMeshes()[0]; // Assuming one material per model for now
    //     auto& mat = mesh.m_material;

    //     std::string diffusePathStr, specularPathStr, normalPathStr;
    //      // Check if a texture exists for a given sampler name in our map
    //     if (mat->textures.count("material.diffuseSampler")) {
    //         // Get the texture's path. Your Texture class needs a public `path` member.
    //         diffusePathStr = mat->textures["material.diffuseSampler"]->path;
    //     }
    //     if (mat->textures.count("material.specularSampler")) {
    //         specularPathStr = mat->textures["material.specularSampler"]->path;
    //     }
    //     if (mat->textures.count("material.normalSampler")) {
    //         normalPathStr = mat->textures["material.normalSampler"]->path;
    //     }

    //     // Create FlatBuffers strings from the paths we found
    //     auto diffusePath = builder.CreateString(diffusePathStr);
    //     auto specularPath = builder.CreateString(specularPathStr);
    //     auto normalPath = builder.CreateString(normalPathStr);
    //     // In a real system, you would get these paths from your material object
        
    //     auto fbMaterial = MyEngine::Scene::CreateMaterial(builder, 
    //         &ToFBVec3(mat->BaseColor), 
    //         mat->shininess,
    //         diffusePath, specularPath, normalPath);

    //     // MeshRenderer
    //     auto assetPath = builder.CreateString(object->model->getAssetPath());
    //     auto fbMeshRenderer = MyEngine::Scene::CreateMeshRenderer(builder, assetPath, fbMaterial);

    //     // Add to component list
    //     componentOffsets.push_back(MyEngine::Scene::CreateComponent(builder, MyEngine::Scene::ComponentData_MeshRenderer, fbMeshRenderer.Union()));
    // }
    // A. MeshRenderer Component
    if (object->model) {
        // --- START OF MULTI-MESH FIX ---
        
        // 1. Create a vector to hold all the serialized material offsets.
        std::vector<flatbuffers::Offset<MyEngine::Scene::Material>> materialOffsets;

        // 2. Loop through every mesh in the model.
        for (auto& mesh : object->model->GetMeshes()) {
            auto& mat = mesh.m_material;

            // Extract texture paths from this specific material
            std::string diffusePathStr, specularPathStr, normalPathStr;
            if (mat->textures.count("material.diffuseSampler")) {
                diffusePathStr = mat->textures["material.diffuseSampler"]->getPath();
            }
            if (mat->textures.count("material.specularSampler")) {
                specularPathStr = mat->textures["material.specularSampler"]->getPath();
            }
            if (mat->textures.count("material.normalSampler")) {
                normalPathStr = mat->textures["material.normalSampler"]->getPath();
            }
            
            auto diffusePath = builder.CreateString(diffusePathStr);
            auto specularPath = builder.CreateString(specularPathStr);
            auto normalPath = builder.CreateString(normalPathStr);
            
            // Create a local variable for the Vec3
            auto fbBaseColor = ToFBVec3(mat->BaseColor);    
            // Serialize this mesh's material
            auto fbMaterial = MyEngine::Scene::CreateMaterial(builder, 
                &fbBaseColor,
                mat->shininess,
                diffusePath, specularPath, normalPath);

            // 3. Add the offset of the created material to our vector.
            materialOffsets.push_back(fbMaterial);
        }
        
        // 4. Create the final FlatBuffers vector of materials.
        auto fbMaterialsVector = builder.CreateVector(materialOffsets);

        // MeshRenderer
        auto assetPath = builder.CreateString(object->model->getAssetPath());
        // 5. Create the MeshRenderer component using the new materials vector.
        auto fbMeshRenderer = MyEngine::Scene::CreateMeshRenderer(builder, assetPath, fbMaterialsVector);

        // Add to the main component list
        componentOffsets.push_back(MyEngine::Scene::CreateComponent(builder, MyEngine::Scene::ComponentData_MeshRenderer, fbMeshRenderer.Union()));
        
        // --- END OF MULTI-MESH FIX ---
    }

    // B. Light Component
    if (auto light = std::dynamic_pointer_cast<Light>(object)) {
        MyEngine::Scene::LightType fbLightType;
        
        // --- START OF LIGHTING FIX ---
        // Check for the most derived types FIRST.
        if (dynamic_cast<SpotLight*>(light.get())) {
            fbLightType = MyEngine::Scene::LightType_Spot;
        } 
        else if (dynamic_cast<PointLight*>(light.get())) {
            fbLightType = MyEngine::Scene::LightType_Point;
        }
        // Now, explicitly check for DirectionalLight.
        else if (dynamic_cast<DirectionalLight*>(light.get())) {
            fbLightType = MyEngine::Scene::LightType_Directional;
        }
        else {
            // This case should ideally not happen if all light types are handled.
            // It's good practice to have a fallback or a warning.
            std::cerr << "Warning: Unknown light type found on GameObject '" << object->name << "'" << std::endl;
            fbLightType = MyEngine::Scene::LightType_Directional; // Default fallback
        }
        // --- END OF LIGHTING FIX ---
        
        float constant = 0, linear = 0, quadratic = 0, cutoff = 0, outer_cutoff = 0;
        if (auto pl = std::dynamic_pointer_cast<PointLight>(light)) {
            constant = pl->constant; linear = pl->linear; quadratic = pl->quadratic;
        }
        if (auto sl = std::dynamic_pointer_cast<SpotLight>(light)) {
            cutoff = sl->cutOff; outer_cutoff = sl->outerCutOff;
        }
        // DirectionalLight has no unique properties to serialize besides what's in the base Light class.
         // Create local variables for all the Vec3s
        auto fbAmbient = ToFBVec3(light->ambient);
        auto fbDiffuse = ToFBVec3(light->diffuse);
        auto fbSpecular = ToFBVec3(light->specular);

        auto fbLight = MyEngine::Scene::CreateLight(builder, fbLightType,
             &fbAmbient, &fbDiffuse, &fbSpecular,
            light->intensity, constant, linear, quadratic, cutoff, outer_cutoff);

        componentOffsets.push_back(MyEngine::Scene::CreateComponent(builder, MyEngine::Scene::ComponentData_Light, fbLight.Union()));
    }

    // --- 2. Serialize Transform ---
    // Create local variables
    auto fbPosition = ToFBVec3(object->position);
    auto fbRotation = ToFBVec3(object->rotation);
    auto fbScale = ToFBVec3(object->scale);

    auto fbTransform = MyEngine::Scene::CreateTransform(builder, 
         &fbPosition,
        &fbRotation,
        &fbScale);

    // --- 3. Serialize GameObject ---
    auto name = builder.CreateString(object->name);
    auto components = builder.CreateVector(componentOffsets);
    uint32_t parentId = 0;
    if (auto parent = object->GetParent().lock()) {
        parentId = parent->GetID();
    }
    
    auto gameObjectOffset = MyEngine::Scene::CreateGameObject(builder, object->GetID(), parentId, name, fbTransform, components);
    gameObjectOffsets.push_back(gameObjectOffset);

    // --- 4. Recurse for Children ---
    for (const auto& child : object->GetChildren()) {
        SerializeObjectAndChildren(child, builder, gameObjectOffsets);
    }
}


// --- LOADING ---

bool SceneSerializer::LoadScene(const std::filesystem::path& filePath, std::vector<std::shared_ptr<GameObject>>& sceneRoots) {
    std::ifstream infile(filePath, std::ios::binary | std::ios::ate);
    if (!infile) {
        std::cerr << "Error: Could not open scene file for reading: " << filePath << std::endl;
        return false;
    }
    auto size = infile.tellg();
    infile.seekg(0, std::ios::beg);
    std::vector<char> buffer(size);
    if (!infile.read(buffer.data(), size)) {
        std::cerr << "Error: Could not read scene file." << std::endl;
        return false;
    }

    auto scene = MyEngine::Scene::GetScene(buffer.data());
    
    sceneRoots.clear();
    std::map<uint32_t, std::shared_ptr<GameObject>> createdObjects;
    std::map<uint32_t, uint32_t> childToParentMap;

    // --- Pass 1: Create all GameObjects and their components ---
    for (const auto* fbGameObject : *scene->game_objects()) {
        auto newObject = DeserializeGameObject(fbGameObject);
        createdObjects[newObject->GetID()] = newObject;
        childToParentMap[newObject->GetID()] = fbGameObject->parent_id();
    }
    
    // --- Pass 2: Stitch the hierarchy ---
    for (const auto& [childId, parentId] : childToParentMap) {
        if (parentId != 0) { // If it has a parent
            auto parentIt = createdObjects.find(parentId);
            auto childIt = createdObjects.find(childId);
            if (parentIt != createdObjects.end() && childIt != createdObjects.end()) {
                parentIt->second->AddChild(childIt->second);
            }
        }
    }
    
    // --- Final Step: Populate the scene roots ---
    for (const auto& [id, object] : createdObjects) {
        if (childToParentMap[id] == 0) {
            sceneRoots.push_back(object);
        }
    }
    
    std::cout << "Scene loaded successfully from " << filePath << std::endl;
    return true;
}



std::shared_ptr<GameObject> SceneSerializer::DeserializeGameObject(const MyEngine::Scene::GameObject* fbGameObject) {
    std::shared_ptr<GameObject> newObject = nullptr;
    
    // --- Pass 1: Determine the specific C++ type and create the object ---
    // This logic is already correct.
    for (const auto* fbComponent : *fbGameObject->components()) {
        if (fbComponent->data_type() == MyEngine::Scene::ComponentData_Light) {
            auto fbLight = fbComponent->data_as_Light();
            switch (fbLight->light_type()) {
                case MyEngine::Scene::LightType_Directional: newObject = std::make_shared<DirectionalLight>(); break;
                case MyEngine::Scene::LightType_Point:       newObject = std::make_shared<PointLight>(); break;
                case MyEngine::Scene::LightType_Spot:        newObject = std::make_shared<SpotLight>(); break;
            }
            break; // Found the primary type, stop looking
        }
    }
    // If no specific type was found, create a base GameObject.
    if (!newObject) {
        newObject = std::make_shared<GameObject>(nullptr);
    }
    
    // --- Pass 2: Apply all component data to the newly created object ---
    for (const auto* fbComponent : *fbGameObject->components()) {
        if (fbComponent->data_type() == MyEngine::Scene::ComponentData_MeshRenderer) {
            auto fbMeshRenderer = fbComponent->data_as_MeshRenderer();
            std::string assetPath = fbMeshRenderer->asset_path()->str();
            
            // The ResourceManager will either load from file or return a cached instance.
            std::shared_ptr<Model> model = m_resourceManager->LoadModel(assetPath);
            newObject->model = model;

            // --- START OF MULTI-MATERIAL & TEXTURE FIX ---
            // Ensure the model and its meshes were loaded correctly.
            if (model && !model->GetMeshes().empty()) {
                auto fbMaterials = fbMeshRenderer->material();
                auto& modelMeshes = model->GetMeshes();

                // Loop through the materials from the scene file and apply them.
                // We use the minimum of the two sizes to avoid crashes if they don't match.
                size_t materialCount = std::min(static_cast<size_t>(fbMaterials->size()), static_cast<size_t>(modelMeshes.size()));
                for (size_t i = 0; i < materialCount; ++i) {
                    const auto* fbMaterial = fbMaterials->Get(i);
                    auto& meshMaterial = modelMeshes[i].m_material;

                    // Apply scalar properties
                    meshMaterial->BaseColor = ToGLMVec3(fbMaterial->base_color());
                    meshMaterial->shininess = fbMaterial->shininess();

                    // Apply textures by loading them through the ResourceManager
                    std::string diffusePath = fbMaterial->diffuse_texture_path()->str();
                    if (!diffusePath.empty()) {
                        meshMaterial->addTexture(m_resourceManager->LoadTexture(diffusePath, Texture::TextureType::Diffuse));
                    }
                    std::string specularPath = fbMaterial->specular_texture_path()->str();
                    if (!specularPath.empty()) {
                        meshMaterial->addTexture(m_resourceManager->LoadTexture(specularPath, Texture::TextureType::Specular));
                    }
                    std::string normalPath = fbMaterial->normal_texture_path()->str();
                    if (!normalPath.empty()) {
                        meshMaterial->addTexture(m_resourceManager->LoadTexture(normalPath, Texture::TextureType::Normal));
                    }
                }
            }
            // --- END OF MULTI-MATERIAL & TEXTURE FIX ---
        }
        else if (fbComponent->data_type() == MyEngine::Scene::ComponentData_Light) {
            // We already know newObject is a Light subclass, so we can safely cast.
            auto light = std::static_pointer_cast<Light>(newObject); 
            auto fbLight = fbComponent->data_as_Light();
            
            // Apply base light properties
            light->ambient = ToGLMVec3(fbLight->ambient());
            light->diffuse = ToGLMVec3(fbLight->diffuse());
            light->specular = ToGLMVec3(fbLight->specular());
            light->intensity = fbLight->intensity();
            
            // --- START OF POINT/SPOT LIGHT FIX ---
            // Apply PointLight-specific properties
            if (auto pointLight = std::dynamic_pointer_cast<PointLight>(light)) {
                pointLight->constant = fbLight->constant();
                pointLight->linear = fbLight->linear();
                pointLight->quadratic = fbLight->quadratic();
            }
            
            // Apply SpotLight-specific properties
            // Note: A SpotLight is also a PointLight, so it will get the properties above too.
            if (auto spotLight = std::dynamic_pointer_cast<SpotLight>(light)) {
                spotLight->cutOff = fbLight->cutoff();
                spotLight->outerCutOff = fbLight->outer_cutoff();
            }
            // --- END OF POINT/SPOT LIGHT FIX ---
        }
    }
    
    // Apply transform, name, and ID (Your existing code is correct)
    newObject->SetID(fbGameObject->id());
    newObject->name = fbGameObject->name()->str();
    auto fbTransform = fbGameObject->transform();
    newObject->position = ToGLMVec3(fbTransform->position());
    newObject->rotation = ToGLMVec3(fbTransform->rotation());
    newObject->scale = ToGLMVec3(fbTransform->scale());
    
    return newObject;
}